#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path : /accueil
    controller: App\Controller\AccueilController::index
rcvb:
    path : /rcvb
    controller: App\Controller\RCVBController::index
